const { chromium } = require('playwright');
const pickM = async (pg, i, label) => { await pg.locator('#rows tr').nth(i).locator('[data-act=pickm]').click(); await pg.locator('#pkGrid .pk[data-name="' + label + '"]').click(); };

const pickC = async (pg, i, label) => { await pg.locator('#rows tr').nth(i).locator('[data-act=pick]').click(); await pg.locator('#pkGrid .pk[data-name="' + label + '"]').click(); };

const http = require('http'), fs = require('fs');
const srv = http.createServer((q, r) => { r.setHeader('content-type', 'text/html'); r.end(fs.readFileSync(__dirname + '/www/dash.html')); }).listen(8765);
const M = n => __dirname + '/media/' + n, URL0 = 'file://' + require('path').resolve(__dirname, '../../public/legacy/index.html');
(async () => {
  const b = await chromium.launch(process.env.PW_CHROMIUM ? { executablePath: process.env.PW_CHROMIUM } : {}); const ctx = await b.newContext({ viewport: { width: 1280, height: 800 }, acceptDownloads: true });
  const errs = [], res = []; const ck = (n, c) => res.push((c ? 'PASS ' : 'FAIL ') + n);
  const p = await ctx.newPage(); p.on('pageerror', e => errs.push('ctl ' + e)); p.on('dialog', d => d.accept());
  await p.goto(URL0);
  // ----- landing page and event creation -----
  ck('landing page shown, no events', await p.isVisible('#homeUI') && !(await p.isVisible('#eventUI')) && (await p.locator('.ev').count()) === 0 && (await p.textContent('#events')).includes('Your next great event starts here'));
  ck('welcome shown, new event in top bar', (await p.textContent('#hello')) === 'Welcome' && (await p.textContent('#helloSub')).includes('Create your first event') && await p.evaluate(() => !!document.querySelector('#homeUI header #btnNew') && !document.querySelector('#hero #btnNew')));
  await p.click('#btnHero'); ck('picture dialog: nothing to remove yet', await p.isDisabled('#heroClear'));
  await p.setInputFiles('#heroFile', M('ballroom.jpg')); await p.waitForTimeout(300);
  ck('welcome picture applied', await p.evaluate(() => { const h = document.getElementById('hero'); return h.classList.contains('has-img') && getComputedStyle(h).backgroundImage.includes('blob:'); }));
  await p.uncheck('#heroLoop'); ck('loop can be hidden', !(await p.isVisible('.loop'))); await p.check('#heroLoop'); await p.click('#heroClose');
  await p.waitForTimeout(3200); ck('strike animation runs once then clears', !(await p.evaluate(() => document.getElementById('hero').classList.contains('strike'))));
  await p.screenshot({ path: 'hero-empty.png' });
  await p.click('#btnNew'); await p.click('#evSave');
  ck('name is required', (await p.textContent('#evErr')).includes('name') && await p.isVisible('#evDlg'));
  await p.fill('#evNameIn', 'TFN Flagship 1'); await p.selectOption('#evType', 'Flagship'); await p.fill('#evDate', '2026-10-26');
  await p.check('#evDlg [name=rmode][value=later]');
  ck('rule fields hidden when deciding later', !(await p.isVisible('#rFields')));
  await p.click('#evSave');
  ck('new event opens on its content tab', await p.isVisible('#eventUI') && await p.isVisible('#viewLib') && (await p.textContent('#evName')) === 'TFN Flagship 1');
  ck('uploads locked until rules set', await p.isVisible('#locked') && !(await p.isVisible('#drop')));
  await p.setInputFiles('#media', [M('Holding Slate.png')]); await p.waitForTimeout(300);
  ck('upload refused while locked', (await p.locator('.asset').count()) === 0 && (await p.textContent('#toast')).includes('Set the content rules'));
  await p.screenshot({ path: 'locked.png' });
  await p.click('#btnSetRules');
  ck('settings dialog opens with rules preselected', (await p.textContent('#evDlgTitle')) === 'Event settings' && await p.isChecked('#evDlg [name=rmode][value=set]') && (await p.inputValue('#rW')) === '1920');
  await p.screenshot({ path: 'dialog.png' });
  await p.click('#evSave');
  ck('unlocked after rules set', await p.isVisible('#drop') && !(await p.isVisible('#locked')) && (await p.textContent('#ruleSum')).includes('exactly 1920×1080'));
  // ----- content -----
  await p.setInputFiles('#media', ['Holding Slate.png', 'Org 1 Title.png', 'Pitch Loop.webm', 'Small Logo.png', 'Animated.gif', 'notes.txt', 'Broken.png', 'Portrait.jpg'].map(M));
  await p.waitForSelector('#rejects li');
  const rej = await p.locator('#rejects li').allTextContents();
  ck('5 bad files rejected with reasons', rej.length === 5 && rej.some(x => x.includes('800×600')) && rej.some(x => x.includes('GIF files are not accepted')) && rej.some(x => x.includes('could not be opened')));
  await p.fill('#webName', 'Pledge dashboard'); await p.fill('#webUrl', 'http://localhost:8765/'); await p.click('#btnWeb');
  ck('4 assets in library', (await p.locator('.asset').count()) === 4);
  await p.locator('.asset', { hasText: 'Image' }).first().locator('button[data-act=hold]').click();
  await p.click('#tabRun'); ck('standby at start', (await p.textContent('#airLab')) === 'STANDBY');
  const heads = () => p.locator('#rhead th').allTextContents(), startOf = i => p.locator('#rows tr').nth(i).locator('td.stt').textContent();
  ck('run view: template shows Who and Audio, no Lighting, running time', JSON.stringify(await heads()) === JSON.stringify(['#', 'Running time', 'Segment', 'Who', 'Content', 'Audio', 'Planned', '']) && (await startOf(0)) === '0:00' && (await startOf(1)) === '30:00' && (await startOf(16)) === '1:54:00');
  await p.click('#btnEdit');
  ck('edit view: all columns', JSON.stringify(await heads()) === JSON.stringify(['#', 'Running time', 'Segment', 'Who', 'Content', 'Music', 'Audio', 'Lighting', 'Transition', 'Type and fixed start', 'Planned', 'Notes', '']));
  const titles = () => p.locator('#rows input[data-f=title]').evaluateAll(l => l.map(i => i.value));
  await p.locator('#rows tr').nth(0).locator('[data-act=ins]').click();
  ck('insert below a row: new segment in place and focused', (await titles()).length === 18 && (await titles())[1] === 'New segment' && await p.evaluate(() => document.activeElement.dataset.f === 'title' && document.activeElement.closest('tr').dataset.i === '1'));
  await p.keyboard.type('Sponsor message');
  ck('typing names the new segment', (await titles())[1] === 'Sponsor message');
  await p.locator('#rows tr').nth(4).locator('.grip').dragTo(p.locator('#rows tr').nth(1), { targetPosition: { x: 200, y: 4 } });
  ck('drag a segment up by its handle', (await titles()).slice(0, 4).join('|') === 'Doors and arrivals|Q&A 1|Sponsor message|Welcome and MC intro');
  await p.locator('#rows tr').nth(1).locator('.grip').dragTo(p.locator('#rows tr').nth(4), { targetPosition: { x: 200, y: 50 } });
  ck('drag it back down', (await titles()).slice(0, 5).join('|') === 'Doors and arrivals|Sponsor message|Welcome and MC intro|Pitch 1|Q&A 1');
  await p.screenshot({ path: 'drag.png' });
  await p.locator('#rows tr').nth(1).locator('[data-act=del]').click();
  ck('delete a segment', (await titles()).length === 17 && (await titles())[1] === 'Welcome and MC intro');
  await p.click('#btnEdit');
  ck('Save leaves edit: Add and Undo hidden, button reads Edit rundown', !(await p.evaluate(() => document.body.classList.contains('edit'))) && !(await p.isVisible('#btnAdd')) && !(await p.isVisible('#btnUndo')) && (await p.textContent('#btnEdit')) === 'Edit rundown' && (await p.textContent('#toast')) === 'Rundown saved.');
  ck('Edit rundown sits above the table, not in the header', await p.evaluate(() => { const b = document.getElementById('btnEdit'); return !b.closest('header') && b.getBoundingClientRect().bottom <= document.querySelector('#viewRun table').getBoundingClientRect().top; }));
  ck('saved changes kept', (await p.locator('#rows tr').count()) === 17);
  await p.click('#btnEdit');
  ck('edit mode: Save, Add at top, nothing to undo yet', (await p.textContent('#btnEdit')) === 'Save' && await p.isVisible('#btnAdd') && await p.isDisabled('#btnUndo'));
  await p.click('#btnAdd'); await p.keyboard.type('Extra item');
  await p.locator('#rows tr').nth(0).locator('[data-act=del]').click();
  await p.locator('#rows tr').nth(2).locator('.grip').dragTo(p.locator('#rows tr').nth(0), { targetPosition: { x: 200, y: 4 } });
  await p.locator('#rows tr').nth(5).locator('input[data-f=who]').fill('Changed'); await p.selectOption('#edFade', '800');
  ck('before undo: 17 rows, reordered', (await titles()).length === 17 && (await titles())[0] === 'Q&A 1' && (await titles())[16] === 'Extra item');
  await p.click('#btnUndo'); ck('undo 1: transition back', (await p.inputValue('#edFade')) === '400');
  await p.click('#btnUndo'); ck('undo 2: typed text back', (await p.locator('#rows tr').nth(5).locator('input[data-f=who]').inputValue()) !== 'Changed');
  await p.click('#btnUndo'); ck('undo 3: drag back', (await titles())[0] === 'Welcome and MC intro');
  await p.click('#btnUndo'); ck('undo 4: deleted segment back', (await titles()).length === 18 && (await titles())[0] === 'Doors and arrivals');
  await p.click('#btnUndo'); ck('undo 5: typed name back', (await titles())[17] === 'New segment');
  await p.click('#btnUndo'); ck('undo 6: added segment gone, nothing left to undo', (await titles()).length === 17 && await p.isDisabled('#btnUndo'));
  await p.screenshot({ path: 'editbar.png' });
  await p.fill('#edStart', '18:00'); await p.locator('#edStart').blur();
  ck('show start gives clock times', (await startOf(0)) === '6:00 PM' && (await startOf(1)) === '6:30 PM' && (await startOf(2)) === '6:40 PM' && (await p.textContent('#edEnd')) === 'Runs 2:24:00, ends 8:24 PM');
  await p.locator('#rows tr').nth(1).locator('input[data-f=dur]').fill('10:30');
  ck('start times follow a duration change while typing', (await startOf(2)) === '6:40:30 PM' && (await p.textContent('#edEnd')) === 'Runs 2:24:30, ends 8:24:30 PM');
  await p.locator('#rows tr').nth(1).locator('input[data-f=dur]').fill('10:00');
  await p.locator('#rows tr').nth(1).locator('input[data-f=who]').fill('Annie (MC)'); await p.locator('#rows tr').nth(1).locator('input[data-f=lx]').fill('Stage wash');
  await p.click('#btnEdit');
  ck('run view after edits: Lighting appears, values shown', (await heads()).includes('Lighting') && (await heads())[1] === 'Start' && (await p.locator('#rows tr').nth(1).locator('td.crew').allTextContents()).join('|') === 'Annie (MC)|MC mic|Stage wash');
  await p.screenshot({ path: 'cols.png' });
  await p.click('#btnEdit'); await p.screenshot({ path: 'cols-edit.png' });
  const sel = i => ({ selectOption: o => pickC(p, i, o.label) });
  await sel(0).selectOption({ label: 'Holding Slate' }); await sel(1).selectOption({ label: 'Org 1 Title' });
  await sel(2).selectOption({ label: 'Pitch Loop' }); await sel(3).selectOption({ label: 'Pledge dashboard' });
  ck('transition pickers: event default and per segment', (await p.locator('#edTrans option').allTextContents()).join('|') === 'Cut|Fade|Dip to black|Slide|Zoom' && (await p.inputValue('#edTrans')) === 'fade' && (await p.locator('#rows tr').nth(0).locator('select[data-f=trans] option').first().textContent()) === 'Event default');
  // ----- music from the cue line, before any audio exists -----
  ck('Music column is in Edit even with no music uploaded yet', (await p.locator('#rhead th').allTextContents()).includes('Music') && (await p.locator('#rows tr').nth(0).locator('[data-act=pickm] .mn').textContent()) === 'Silence');
  await p.locator('#rows tr').nth(0).locator('[data-act=pickm]').click();
  ck('music picker: silence only, upload offered, no link section', (await p.textContent('#pkTitle')) === 'Music for "Doors and arrivals"' && (await p.locator('#pkGrid .pk').count()) === 1 && (await p.textContent('#pkUpload')) === 'Upload a music file' && !(await p.isVisible('#pkLink')));
  await p.setInputFiles('#pkFile', M('Org 1 Title.png')); await p.waitForFunction(() => document.getElementById('pkErr').textContent.length > 0);
  ck('a picture is refused as music', (await p.textContent('#pkErr')) === 'That is not a music file.' && await p.isVisible('#pickDlg'));
  await p.setInputFiles('#pkFile', M('Arrivals.wav')); await p.waitForFunction(() => !document.getElementById('pickDlg').open);
  ck('uploading from the cue line adds the track and assigns it', (await p.locator('#rows tr').nth(0).locator('[data-act=pickm] .mn').textContent()) === '♪ Arrivals' && (await p.textContent('#tabLib')) === 'Content (5)');
  await p.locator('#rows tr').nth(0).locator('[data-act=pickm]').click(); await p.screenshot({ path: 'music-picker.png' });
  ck('music picker lists the track with its length', (await p.locator('#pkGrid .pk.sel').getAttribute('data-name')) === 'Arrivals' && (await p.locator('#pkGrid .pk.sel small').textContent()) === '0:02, loops');
  await p.locator('#pkGrid .pk[data-name="None (silence)"]').click();
  ck('back to silence', (await p.locator('#rows tr').nth(0).locator('[data-act=pickm] .mn').textContent()) === 'Silence');
  await p.locator('#rows tr').nth(5).locator('[data-act=pick]').click(); await p.setInputFiles('#pkFile', M('Holding Slate.png')); await p.waitForFunction(() => !document.getElementById('pickDlg').open);
  ck('uploading a picture from the content picker adds and assigns it', (await p.locator('#rows tr').nth(5).locator('.pickbtn .nm').textContent()) === 'Holding Slate' && (await p.textContent('#tabLib')) === 'Content (6)');
  await p.click('#btnUndo'); await p.click('#btnUndo'); await p.click('#btnUndo');
  await p.click('#tabLib'); await p.locator('.asset:has(input[value="Arrivals"])').locator('[data-act=del]').click(); await p.locator('.asset:has(input[value="Holding Slate"])').nth(1).locator('[data-act=del]').click();
  await p.click('#tabRun'); await p.click('#btnEdit');
  // ----- content picker -----
  await p.locator('#rows tr').nth(5).locator('[data-act=pick]').click();
  ck('clicking a content cell opens the gallery picker', await p.isVisible('#pickDlg') && (await p.textContent('#pkTitle')) === 'Content for "Q&A 2"' && (await p.locator('#pkGrid .pk').count()) === 5 && (await p.locator('#pkGrid .pk.sel').getAttribute('data-name')) === 'None (black)' && (await p.locator('#pkGrid .pk img.th').count()) === 2);
  await p.screenshot({ path: 'picker.png' });
  await p.fill('#pkFind', 'org'); ck('picker search narrows the list', (await p.locator('#pkGrid .pk').count()) === 1 && (await p.locator('#pkGrid .pk').getAttribute('data-name')) === 'Org 1 Title');
  await p.locator('#pkGrid .pk').click();
  ck('choosing a tile assigns it and closes the picker', !(await p.isVisible('#pickDlg')) && (await p.locator('#rows tr').nth(5).locator('.pickbtn .nm').textContent()) === 'Org 1 Title');
  await p.locator('#rows tr').nth(5).locator('[data-act=pick]').click(); await p.click('#pkAdd');
  ck('a link needs an address', (await p.textContent('#pkErr')).includes('Paste the web address'));
  await p.fill('#pkName', 'Event Butler control'); await p.fill('#pkUrl', 'http://localhost:8765/control'); await p.click('#pkAdd');
  ck('add a link from the picker: added to content and used on the row', !(await p.isVisible('#pickDlg')) && (await p.locator('#rows tr').nth(5).locator('.pickbtn .nm').textContent()) === 'Event Butler control' && (await p.textContent('#tabLib')) === 'Content (5)');
  await p.locator('#rows tr').nth(6).locator('[data-act=pick]').click(); await p.fill('#pkUrl', 'http://localhost:8765/control'); await p.click('#pkAdd');
  ck('the same link is reused, not added twice', (await p.textContent('#tabLib')) === 'Content (5)' && (await p.locator('#rows tr').nth(6).locator('.pickbtn .nm').textContent()) === 'Event Butler control');
  await p.locator('#rows tr').nth(6).locator('[data-act=pick]').click(); await p.fill('#pkName', 'Hosted logo'); await p.fill('#pkUrl', 'http://localhost:8765/logo.png'); await p.click('#pkAdd');
  ck('a link to a picture is treated as a picture', (await p.locator('#rows tr').nth(6).locator('.pickbtn img.th').count()) === 1 && (await p.textContent('#tabLib')) === 'Content (6)');
  await p.click('#btnUndo'); await p.click('#btnUndo'); await p.click('#btnUndo'); await p.click('#btnUndo');
  ck('undo steps the picker choices back', (await p.locator('#rows tr').nth(5).locator('.pickbtn .nm').textContent()) === 'Black' && (await p.locator('#rows tr').nth(6).locator('.pickbtn .nm').textContent()) === 'Black');
  await p.click('#tabLib'); for (const n of ['Event Butler control', 'Hosted logo']) await p.locator('.asset:has(input[value="' + n + '"])').locator('[data-act=del]').click();
  await p.click('#tabRun'); await p.click('#btnEdit');
  await p.selectOption('#edTrans', 'slide'); const tsel = (i, v) => p.locator('#rows tr').nth(i).locator('select[data-f=trans]').selectOption(v);
  await tsel(1, 'dip'); await tsel(2, 'zoom'); await tsel(3, 'cut');
  await p.click('#btnEdit');
  const [o] = await Promise.all([ctx.waitForEvent('page'), p.click('#btnOut')]);
  o.on('pageerror', e => errs.push('out ' + e)); await o.waitForLoadState();
  await p.waitForFunction(() => document.getElementById('outTxt').textContent === 'Output live', null, { timeout: 5000 });
  const top = () => o.evaluate(() => { const l = [...document.querySelectorAll('.layer')].filter(e => getComputedStyle(e).opacity === '1').sort((a, b) => (+b.style.zIndex) - (+a.style.zIndex))[0]; return l ? l.tagName : 'BLACK'; });
  const mon = id => p.evaluate(id => { const e = document.getElementById(id).querySelector('img,video,iframe'); return e ? e.tagName : 'BLACK'; }, id);
  const settle = () => o.waitForTimeout(1300);
  await p.keyboard.press('Space'); await settle(); ck('slide ends square on screen', await o.evaluate(() => [...document.querySelectorAll('.layer')].filter(e => getComputedStyle(e).opacity === '1').every(e => ['none', 'matrix(1, 0, 0, 1, 0, 0)'].includes(getComputedStyle(e).transform)) && document.querySelectorAll('.layer:not(iframe)').length === 1));
  ck('take 1 -> image, monitors follow', (await top()) === 'IMG' && (await mon('monPgm')) === 'IMG' && (await mon('monPvw')) === 'IMG');
  await p.evaluate(() => { const s = document.getElementById('vidVol'); s.value = 50; s.dispatchEvent(new Event('input', { bubbles: true })); });
  await p.keyboard.press('Space'); await p.keyboard.press('Space'); await settle(); ck('take 3 -> video', (await top()) === 'VIDEO');
  const vv = () => o.evaluate(() => document.querySelector('video').volume);
  ck('video fader sets the video level on the output', (await vv()) === 0.5);
  await p.click('#masMute'); await o.waitForTimeout(300); ck('master mute silences the video', (await vv()) === 0 && (await p.textContent('#masMute')) === 'Unmute');
  await p.click('#masMute'); await o.waitForTimeout(300); ck('master unmute restores it', (await vv()) === 0.5);
  await p.keyboard.press('Space'); await settle(); ck('take 4 -> web page', (await top()) === 'IFRAME' && (await mon('monPgm')) === 'IFRAME');
  await p.keyboard.press('h'); await settle(); ck('H -> holding image', (await top()) === 'IMG');
  await p.keyboard.press('h'); await settle(); ck('H again -> back to web', (await top()) === 'IFRAME');
  await p.keyboard.press('Space'); await settle(); ck('no content -> black', (await top()) === 'BLACK');
  await p.locator('#rows tr').nth(1).dblclick(); await settle(); ck('double-click row -> image', (await top()) === 'IMG');
  await p.reload(); await p.waitForFunction(() => document.getElementById('outTxt').textContent === 'Output live', null, { timeout: 6000 });
  ck('on-air card shows who and audio', (await p.textContent('#airSub')).includes('Annie (MC)') && (await p.textContent('#airSub')).includes('Audio: MC mic'));
  ck('reload returns to the open event, output unchanged', await p.isVisible('#eventUI') && (await p.locator('#rows tr').nth(2).locator('.nm').textContent()) === 'Pitch Loop' && (await top()) === 'IMG' && (await p.textContent('#airTtl')) === 'Welcome and MC intro');
  await p.keyboard.press('Space'); await settle(); ck('take after reload works', (await top()) === 'VIDEO');
  await o.reload(); await o.waitForTimeout(2600); ck('output reload restores content', (await top()) === 'VIDEO');
  const [dl] = await Promise.all([p.waitForEvent('download'), p.evaluate(() => document.getElementById('btnExport').click())]); await dl.saveAs(require('path').join(__dirname, 'out') + '/show.json');
  const pkg = JSON.parse(fs.readFileSync(require('path').join(__dirname, 'out') + '/show.json')); ck('export has content, rules, type', pkg.assets.length === 4 && pkg.rules.w === 1920 && pkg.type === 'Flagship' && pkg.date === '2026-10-26' && pkg.showStart === '18:00' && pkg.items[1].who === 'Annie (MC)');
  // ----- settings: change rules -----
  await p.click('#tabLib'); await p.click('#btnRules');
  ck('cannot withdraw rules once files exist', await p.isDisabled('#evDlg [name=rmode][value=later]'));
  await p.selectOption('#rRes', 'any'); await p.click('#evSave');
  await p.setInputFiles('#media', [M('Small Logo.png')]); await p.waitForTimeout(400);
  ck('rules loosened -> small logo accepted', (await p.locator('.asset', { hasText: '800×600' }).count()) === 1);
  await p.evaluate(() => document.getElementById('btnSettings').click()); await p.selectOption('#rRes', 'exact'); await p.fill('#rMax', '1'); await p.fill('#evNameIn', 'TFN Flagship One'); await p.click('#evSave');
  ck('settings: rename + tighten flags old content', (await p.textContent('#evName')) === 'TFN Flagship One' && (await p.locator('.asset .out').count()) === 1 && (await p.textContent('#ruleSum')).includes('up to 1 MB'));
  // ----- music -----
  await p.evaluate(() => document.getElementById('btnSettings').click()); await p.fill('#rMax', '5'); await p.click('#evSave');
  ck('content page is quiet: no monitors, sound bar or sources', !(await p.isVisible('#musBar')) && !(await p.isVisible('#monPgm')) && !(await p.isVisible('#srcWrap')) && !(await p.isVisible('#btnTake')) && (await p.textContent('#viewTitle')) === 'Content');
  await p.setInputFiles('#media', [M('Walk In.wav'), M('Sting.wav')]); await p.waitForFunction(() => document.querySelectorAll('.asset audio.prev').length === 2);
  ck('audio accepted, shown as a player with its length', (await p.locator('.asset', { hasText: 'Audio · 0:03' }).count()) === 1 && (await p.locator('.src').count()) === 5);
  const card = n => p.locator('.asset:has(input[value="' + n + '"])');
  await card('Walk In').locator('select[data-k=fade]').selectOption('1'); await card('Sting').locator('input[data-k=loop]').uncheck();
  await p.click('#tabRun'); await p.click('#btnEdit');
  ck('edit view has a Music column, content picker has no audio', (await p.locator('#rhead th').allTextContents()).includes('Music') && await (async () => { await p.locator('#rows tr').nth(0).locator('[data-act=pick]').click(); const n = await p.locator('#pkGrid .pk').evaluateAll(l => l.map(b => b.dataset.name)); await p.click('#pkCancel'); return !n.includes('Walk In') && n.includes('Holding Slate'); })());
  await pickM(p, 2, 'Walk In'); await pickM(p, 4, 'Sting');
  await p.selectOption('#edHoldMus', { label: 'Walk In' }); await p.click('#btnEdit');
  const mus = () => p.textContent('#musName');
  ck('music starts for the segment on air', (await mus()) === 'Walk In, looping' && await p.evaluate(() => document.getElementById('musBar').classList.contains('on')));
  ck('run view shows the track and the cards mention it', (await p.locator('#rows tr').nth(2).locator('td.crew').allTextContents()).some(x => x === '♪ Walk In') && (await p.textContent('#airSub')).includes('♪ Walk In'));
  await p.keyboard.press('Space'); ck('next segment has no music: silence', (await mus()) === 'Silence');
  await p.keyboard.press('Space'); ck('one-shot track is not marked looping', (await mus()) === 'Sting');
  await p.keyboard.press('h'); ck('holding plays the holding music', (await mus()) === 'Walk In, looping');
  await p.keyboard.press('h'); ck('back from holding returns to the segment track', (await mus()) === 'Sting');
  ck('rundown page has monitors, sound bar and the rail', await p.isVisible('#musBar') && await p.isVisible('#monPgm') && await p.isVisible('.rail') && (await p.getAttribute('#navRun', 'aria-pressed')) === 'true' && (await p.textContent('#viewTitle')) === 'Rundown' && !(await p.isVisible('#airMini')));
  await p.screenshot({ path: 'rail-run.png' });
  await p.click('#navLib'); await p.waitForTimeout(400);
  ck('away from the rundown, the header says what is on air', await p.isVisible('#airMini') && (await p.textContent('#airMiniTxt')).startsWith('On air: Pitch 2') && (await p.getAttribute('#navLib', 'aria-pressed')) === 'true');
  await p.screenshot({ path: 'rail-content.png' });
  await p.click('#navSet');
  ck('settings page: event summary and five sections', (await p.locator('.setcard').count()) === 5 && (await p.textContent('#setEvent')).includes('TFN Flagship One') && (await p.textContent('#setEvent')).includes('This event accepts') && !(await p.isVisible('#monPgm')) && !(await p.isVisible('#lib')) && (await p.textContent('#cloudTxt3')) === 'Cloud: not connected.');
  await p.screenshot({ path: 'rail-settings.png' });
  await p.click('#btnSettings'); ck('settings page opens event details', await p.isVisible('#evDlg') && (await p.textContent('#evDlgTitle')) === 'Event settings'); await p.click('#evCancel');
  await p.click('#btnCloud3'); ck('settings page opens cloud sign-in', await p.isVisible('#cloudDlg')); await p.click('#cdClose');
  ck('header no longer carries settings, export or restart', await p.evaluate(() => !document.querySelector('#eventUI header #btnSettings, #eventUI header #btnExport, #eventUI header #btnReset, #eventUI header #btnHome')));
  await p.click('#navRun'); ck('back to the rundown, still on air with music', (await p.textContent('#airTtl')) === 'Pitch 2' && (await mus()) === 'Sting' && await p.isVisible('#monPgm'));
  await p.click('#musMute'); ck('mute toggles', (await p.textContent('#musMute')) === 'Unmute'); await p.click('#musMute');
  await p.reload(); await p.waitForTimeout(500); ck('fader positions are remembered', (await p.inputValue('#vidVol')) === '50' && (await p.inputValue('#musVol')) === '80'); await p.click('#clock');
  await p.locator('#musBar').screenshot({ path: 'soundbar.png' });
  await p.locator('#viewRun').screenshot({ path: 'music-table.png' }); await p.locator('#musBar').screenshot({ path: 'music-bar.png' });
  await p.locator('#rows tr').nth(2).dblclick(); await p.reload(); await p.waitForTimeout(600);
  ck('after a reload the music waits for a click, then resumes', ['Click anywhere to start the music', 'Walk In, looping'].includes(await mus()));
  await p.click('#clock'); await p.waitForTimeout(300); ck('music resumes after the click', (await mus()) === 'Walk In, looping');
  await p.click('#btnEdit'); await p.locator('#rows tr').nth(2).locator('[data-act=up]').click(); await p.click('#btnEdit');
  ck('moving the on-air segment keeps it on air', (await p.textContent('#airTtl')) === 'Pitch 1' && (await p.locator('#rows tr.air').getAttribute('data-i')) === '1' && (await p.textContent('#musName')) === 'Walk In, looping');
  await p.click('#btnEdit'); await p.locator('#rows tr').nth(1).locator('[data-act=down]').click(); await p.click('#btnEdit');
  await p.click('#tabLib'); await card('Sting').locator('[data-act=del]').click(); await p.click('#tabRun');
  ck('deleting a track clears it from the rundown', (await p.locator('#rows tr').nth(4).locator('td.crew').allTextContents()).every(x => !x.includes('Sting')));
  await p.evaluate(() => document.getElementById('btnSettings').click()); await p.uncheck('#evDlg [data-r=audio]'); await p.click('#evSave'); await p.click('#tabLib');
  await p.setInputFiles('#media', [M('Sting.wav')]); await p.waitForSelector('#rejects li');
  ck('audio can be switched off in the rules', (await p.textContent('#rejects li')).includes('WAV files are not accepted'));
  await p.click('#tabRun');
  // ----- back to landing page, second event is separate -----
  await p.click('#btnHome'); await settle();
  ck('back on landing page, screen to black', await p.isVisible('#homeUI') && (await top()) === 'BLACK' && (await p.locator('.ev').count()) === 1);
  ck('event card shows details', await p.evaluate(() => { const t = document.querySelector('.ev').textContent; return t.includes('TFN Flagship One') && t.includes('Flagship') && t.includes('2026') && t.includes('6 content items') && t.includes('1920×1080'); }));
  await p.click('#btnNew'); await p.fill('#evNameIn', 'TFN Flagship 2'); await p.selectOption('#evType', 'Pitch night'); await p.click('#evSave');
  ck('second event starts with empty, unlocked library', (await p.textContent('#tabLib')) === 'Content (0)' && await p.isVisible('#drop') && (await p.locator('.src').count()) === 0);
  await p.setInputFiles('#media', [M('Org 1 Title.png')]); await p.waitForTimeout(400);
  await p.click('#btnHome');
  await p.click('#btnNew'); await p.fill('#evNameIn', 'Undecided event'); await p.check('#evDlg [name=rmode][value=later]'); await p.click('#evSave'); await p.click('#btnHome');
  ck('three events laid out', (await p.locator('.ev').count()) === 3 && (await p.locator('.ev .rule.unset').count()) === 1);
  ck('welcome names the next event', (await p.textContent('#helloSub')).includes('TFN Flagship One is in') && (await p.textContent('#helloSub')).includes('One event still needs content rules') && (await p.textContent('#btnNext')) === 'Open TFN Flagship One' && (await p.locator('.ev.next').count()) === 1 && (await p.textContent('#evCount')) === '(3)');
  ck('upcoming event listed first', (await p.locator('.ev h3').first().textContent()) === 'TFN Flagship One');
  await p.screenshot({ path: 'home.png' });
  await p.click('#btnNext'); ck('open-next button opens it', (await p.textContent('#evName')) === 'TFN Flagship One'); await p.click('#btnHome');
  await p.locator('.ev', { hasText: 'TFN Flagship One' }).locator('[data-act=open]').click();
  ck('event 1 content untouched by event 2', (await p.textContent('#tabLib')) === 'Content (6)' && (await p.textContent('#airTtl')) === 'Pitch 1');
  await p.click('#btnHome');
  await p.locator('.ev', { hasText: 'Undecided' }).locator('[data-act=edit]').click();
  ck('edit from landing page: rules still undecided', await p.isChecked('#evDlg [name=rmode][value=later]'));
  await p.click('#evCancel');
  await p.locator('.ev', { hasText: 'TFN Flagship 2' }).locator('[data-act=del]').click();
  ck('delete event', (await p.locator('.ev').count()) === 2 && (await p.locator('.ev', { hasText: 'TFN Flagship 2' }).count()) === 0);
  ck('deleted event content removed from storage', await p.evaluate(() => new Promise(r => { const q = indexedDB.open('neonloop'); q.onsuccess = () => { const g = q.result.transaction('assets').objectStore('assets').getAll(); g.onsuccess = () => r(g.result.length === 7 && g.result.every(a => a.eventId)); }; })));
  await p.reload(); ck('landing page persists after reload', await p.isVisible('#homeUI') && (await p.locator('.ev').count()) === 2);
  ck('welcome picture persists and is not event content', await p.evaluate(() => document.getElementById('hero').classList.contains('has-img')) && (await p.locator('.ev', { hasText: '6 content items' }).count()) === 1);
  await p.waitForTimeout(3200); await p.screenshot({ path: 'hero-img.png' });
  await p.click('#btnHero'); await p.click('#heroClear'); ck('picture removed', !(await p.evaluate(() => document.getElementById('hero').classList.contains('has-img')))); await p.click('#heroClose');
  // ----- import as a new event, phone width -----
  const ctx2 = await b.newContext({ viewport: { width: 390, height: 800 } }); const q = await ctx2.newPage(); q.on('pageerror', e => errs.push('imp ' + e));
  await q.goto(URL0); await q.setInputFiles('#file', require('path').join(__dirname, 'out') + '/show.json'); await q.waitForSelector('.ev');
  ck('import creates an event', (await q.locator('.ev').count()) === 1 && (await q.textContent('.ev h3')) === 'TFN Flagship 1');
  ck('390 landing no horizontal scroll', await q.evaluate(() => document.documentElement.scrollWidth <= innerWidth)); await q.screenshot({ path: 'home390.png' });
  await q.click('.ev [data-act=open]');
  ck('import keeps start time and crew columns', await q.evaluate(() => { const e = JSON.parse(localStorage.getItem('neonloop.v3')).events[0]; return e.showStart === '18:00' && e.items[1].lx === 'Stage wash'; }));
  ck('imported event has content and rundown', (await q.locator('#rows tr').nth(0).locator('img.th').count()) === 1 && (await q.textContent('#tabLib')) === 'Content (4)');
  ck('390 event no horizontal scroll', await q.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await q.evaluate(() => document.getElementById('btnSettings').click()); ck('390 dialog fits', await q.evaluate(() => { const r = document.getElementById('evDlg').getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth; })); await q.screenshot({ path: 'dlg390.png' });
  // ----- upgrade from the previous single-event version -----
  const ctx3 = await b.newContext(); const u = await ctx3.newPage(); u.on('pageerror', e => errs.push('mig ' + e));
  await u.addInitScript(() => { if (!localStorage.getItem('neonloop.v3')) localStorage.setItem('neonloop.v2', JSON.stringify({ state: { eventName: 'Old Show', holdingAsset: '', fadeMs: 0, items: [{ title: 'Only item', asset: '', dur: 60, notes: '' }] }, run: { current: 0, cued: 1, startedAt: Date.now(), hold: false } })); });
  await u.goto(URL0); await u.waitForSelector('#eventUI', { state: 'visible' });
  ck('earlier rundown carried over as an event', (await u.textContent('#evName')) === 'Old Show' && (await u.locator('#rows tr').count()) === 1 && (await u.textContent('#airTtl')) === 'Only item');
  ck('no page errors', errs.length === 0); if (errs.length) console.log(errs);
  console.log(res.join('\n')); await b.close(); srv.close(); process.exit(res.some(r => r.startsWith('FAIL')) ? 1 : 0);
})().catch(e => { console.error(e); process.exit(2); });
