const { chromium } = require('playwright');
const fs = require('fs');
const M = n => __dirname + '/media/' + n, URL0 = 'file://' + require('path').resolve(__dirname, '../../public/legacy/index.html');
(async () => {
  const b = await chromium.launch(process.env.PW_CHROMIUM ? { executablePath: process.env.PW_CHROMIUM } : {}); const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, acceptDownloads: true });
  const errs = [], res = []; const ck = (n, c) => res.push((c ? 'PASS ' : 'FAIL ') + n);
  const p = await ctx.newPage(); p.on('pageerror', e => errs.push(String(e))); let answer = null; p.on('dialog', d => d.accept(answer == null ? undefined : answer));
  await p.goto(URL0); await p.click('#btnNew'); await p.fill('#evNameIn', 'TFN Flagship 1'); await p.click('#evSave');
  const ev = () => p.evaluate(() => JSON.parse(localStorage.getItem('neonloop.v3')).events[0]);

  // ---------- guests ----------
  await p.click('#navGst');
  ck('guests page: empty, quiet (no monitors)', (await p.textContent('#viewTitle')) === 'Guests' && await p.isVisible('#gEmpty') && !(await p.isVisible('#monPgm')) && !(await p.isVisible('#musBar')));
  await p.click('#gImport'); await p.setInputFiles('#impFile', M('guests.xlsx')); await p.waitForSelector('#impMap select');
  const map = await p.evaluate(() => Object.fromEntries([...document.querySelectorAll('#impMap select')].map(s => [s.dataset.f, s.options[s.selectedIndex].textContent])));
  ck('Excel file read, columns matched by their headings', map.first === 'First Name' && map.last === 'Last Name' && map.email === 'Email' && map.phone === 'Mobile' && map.company === 'Company' && map.table === 'Table' && map.full === 'Not in this file' && (await p.textContent('#impGo')) === 'Import 6 guests');
  await p.click('#impGo');
  let e = await ev();
  ck('6 guests imported; Excel mobile numbers get their leading 0 back', e.guests.length === 6 && e.guests.find(g => g.first === 'Asad').phone === '0434040767' && e.guests.find(g => g.first === 'Maddi').phone === '0434 399 961' && e.guests.find(g => g.first === 'Asad').table === '1' && (await p.textContent('#gCount')) === '0 of 6 arrived');
  await p.click('#gImport'); await p.setInputFiles('#impFile', M('guests2.csv')); await p.waitForSelector('#impMap select');
  ck('CSV with a single Name column is matched as full name', await p.evaluate(() => { const s = document.querySelector('#impMap select[data-f=full]'); return s.options[s.selectedIndex].textContent === 'Name'; }));
  await p.click('#impGo'); e = await ev();
  ck('second import adds new people and updates existing ones, no duplicates', e.guests.length === 8 && e.guests.find(g => g.first === 'Asad').company === 'Hope Network Ltd' && e.guests.find(g => g.first === 'Asad').table === '7' && !!e.guests.find(g => g.first === 'Emma' && g.last === 'Barham') && (await p.textContent('#toast')).startsWith('2 guests added, 1 already on the list updated'));
  await p.click('#gImport'); await p.fill('#impPaste', 'First name\tLast name\tCompany\nZoe\tZhang\tLynxx'); await p.waitForSelector('#impMap select'); await p.click('#impGo');
  ck('pasted cells import too', (await ev()).guests.length === 9);
  await p.fill('#gFind', 'bupa'); ck('search filters by company', (await p.locator('#gRows tr').count()) === 2);
  await p.fill('#gFind', 'nicola'); await p.press('#gFind', 'Enter');
  ck('type a name and press Enter to check in', (await p.textContent('#gCount')) === '1 of 9 arrived' && (await p.inputValue('#gFind')) === '');
  await p.locator('#gRows tr', { hasText: 'Luke Anderson' }).locator('[data-a=in]').click();
  ck('check-in button', (await p.textContent('#gCount')) === '2 of 9 arrived' && (await p.locator('#gRows tr.in').count()) === 2);
  await p.click('#gAdd'); await p.click('#gSave'); ck('a guest needs a name', (await p.textContent('#gErr')).includes('Enter a name'));
  await p.fill('#g_first', 'Wendy'); await p.fill('#g_last', 'Walker'); await p.fill('#g_tag', 'BAND-0042'); await p.click('#gSave');
  e = await ev(); const wendy = e.guests.find(g => g.first === 'Wendy');
  ck('walk-in added at the door is checked in straight away', !!wendy && wendy.walkIn && wendy.arrived > 0 && wendy.tag === 'BAND-0042' && (await p.textContent('#gCount')) === '3 of 10 arrived');
  await p.click('#gAdd'); await p.fill('#g_first', 'Dup'); await p.fill('#g_tag', 'BAND-0042'); await p.click('#gSave');
  ck('a wristband cannot be given to two people', (await p.textContent('#gErr')).includes('already given to Wendy Walker') && (await ev()).guests.length === 10); await p.click('#gCancel');
  await p.locator('#gRows .gn', { hasText: 'Paul Anscombe' }).click(); await p.fill('#g_company', 'Anscombe & Co'); await p.click('#gSave');
  ck('edit a guest', (await ev()).guests.find(g => g.first === 'Paul').company === 'Anscombe & Co');
  await p.screenshot({ path: 'guests.png' });
  const [d1] = await Promise.all([p.waitForEvent('download'), p.click('#gExport')]); await d1.saveAs(require('path').join(__dirname, 'out') + '/att.csv'); const att = fs.readFileSync(require('path').join(__dirname, 'out') + '/att.csv', 'utf8');
  ck('attendance export', att.includes('First name,Last name,Company') && att.includes('Nicola,Archer,Equity Trustees') && att.includes(',Yes,') && att.includes('Anscombe & Co') && att.split('\r\n').length === 11);

  // ---------- pledges: people pledge their own money ----------
  await p.click('#navPlg');
  ck('pledges page asks for setup first', await p.isVisible('#plNone') && !(await p.isVisible('#plForm')));
  await p.click('#plSetupBtn2'); await p.click('#psSave'); ck('needs an organisation', (await p.textContent('#psErr')).includes('at least one'));
  const names = ['River Nile', 'Hope Network', 'Happy Brain'];
  for (let i = 0; i < 3; i++) await p.locator('#psOrgs input[data-k=name]').nth(i).fill(names[i]);
  await p.locator('#psOrgs input[data-k=match]').nth(1).fill('10000'); await p.click('#psSave');
  ck('organisations set up; first one selected', (await p.locator('#plOrgs button').allTextContents()).join('|') === names.join('|') && (await p.getAttribute('#plOrgs button >> nth=0', 'aria-pressed')) === 'true');
  await p.click('#plGo'); ck('amount is required', (await p.textContent('#plMsg')) === 'Enter the amount.');
  await p.fill('#plAmt', '500'); await p.click('#plGo'); ck('a donor is required unless anonymous', (await p.textContent('#plMsg')).includes('Choose who the pledge is from'));
  await p.fill('#plWho', 'alder'); await p.waitForSelector('#plSug button');
  ck('typing suggests matching guests', (await p.locator('#plSug button').count()) === 4 && (await p.locator('#plSug button').first().textContent()).includes('Alderuccio'));
  await p.keyboard.press('Enter');
  ck('Enter picks the donor and moves to the amount', (await p.textContent('#plChipTxt')) === 'Loren Alderuccio (Bupa)' && await p.evaluate(() => document.activeElement.id === 'plAmt'));
  await p.keyboard.press('Enter');
  ck('first pledge recorded', (await p.textContent('#plMsg')) === 'Recorded $500 for River Nile from Loren Alderuccio (Bupa).' && (await p.locator('.prow').count()) === 1 && (await p.inputValue('#plAmt')) === '');
  await p.keyboard.press('ArrowDown'); await p.keyboard.type('200'); await p.keyboard.press('Enter');
  ck('same donor, next organisation, without touching the mouse', (await p.locator('.prow').count()) === 2 && (await p.locator('.prow').first().textContent()).includes('Hope Network') && (await p.locator('.prow').first().textContent()).includes('$200'));
  await p.click('#plChipX'); await p.fill('#plWho', 'BAND-0042'); await p.keyboard.press('Enter');
  ck('a tapped wristband ID picks its guest', (await p.textContent('#plChipTxt')) === 'Wendy Walker');
  await p.click('#plQuick button >> nth=3'); await p.keyboard.press('Enter');
  await p.click('#plChipX'); await p.fill('#plWho', 'Swinburne University'); await p.locator('#plSug button', { hasText: 'as a company or donor' }).click(); await p.fill('#plAmt', '12,000'); await p.keyboard.press('Enter');
  e = await ev();
  ck('pledge on behalf of a company adds it as a donor, not an attendee', e.guests.some(g => g.kind === 'org' && g.company === 'Swinburne University') && e.pledges.length === 4 && e.pledges[3].amount === 12000 && e.pledges[3].donorName === 'Swinburne University');
  await p.click('#plChipX'); await p.check('#plAnon'); await p.fill('#plAmt', '50'); await p.keyboard.press('Enter'); await p.uncheck('#plAnon');
  const tot = await p.textContent('#pTotals');
  ck('totals with matching: Hope Network 13,200 pledged, capped at 10,000 matched', tot.includes('$23,750') && tot.includes('$13,750 pledged plus $10,000 matched') && tot.includes('$10,000 of $10,000 matched') && tot.includes('5 pledges'));
  answer = '250'; await p.locator('.prow', { hasText: '$200' }).locator('[data-a=edit]').click(); answer = null;
  ck('amend a pledge', (await ev()).pledges[1].amount === 250 && (await p.textContent('#pTotals')).includes('$23,800'));
  await p.locator('.prow', { hasText: 'Anonymous' }).locator('[data-a=void]').click();
  ck('remove a pledge', (await ev()).pledges.length === 4 && (await p.textContent('#pTotals')).includes('$23,750'));
  await p.screenshot({ path: 'pledges.png' });
  const [d2] = await Promise.all([p.waitForEvent('download'), p.click('#plExport')]); await d2.saveAs(require('path').join(__dirname, 'out') + '/pl.csv'); const pl = fs.readFileSync(require('path').join(__dirname, 'out') + '/pl.csv', 'utf8');
  ck('pledge export has donor details for reconciling', pl.includes('Organisation,Amount,Donor') && pl.includes('River Nile,500,Loren Alderuccio (Bupa),No,Own money,Loren,Alderuccio,Bupa,loren@example.com,0434340891') && pl.split('\r\n').length === 5);
  await p.click('#navGst'); ck('walk-in from the pledge screen and company donor show on the guest list', (await p.locator('#gRows tr', { hasText: 'Donor only' }).count()) === 1 && (await p.textContent('#gCount')) === '3 of 10 arrived');
  await p.reload(); await p.click('#navPlg'); ck('pledges survive a reload', (await p.locator('.prow').count()) === 4);

  // ---------- pledges: a company budget ----------
  await p.click('#btnHome'); await p.click('#btnNew'); await p.fill('#evNameIn', 'AMP Foundation'); await p.click('#evSave'); await p.click('#navPlg'); await p.click('#plSetupBtn2');
  for (let i = 0; i < 2; i++) await p.locator('#psOrgs input[data-k=name]').nth(i).fill(['Ecomind', 'Fruit Share'][i]);
  await p.check('#plDlg [name=fmode][value=budget]'); await p.click('#psSave'); ck('a budget event needs a budget', (await p.textContent('#psErr')).includes('Enter the company budget'));
  await p.fill('#psCompany', 'AMP'); await p.fill('#psBudget', '50000'); await p.fill('#psAllow', '30000'); await p.click('#psSave');
  ck('budget panel shows what is left', (await p.textContent('#pTotals')).includes('AMP budget') && (await p.textContent('#pTotals')).includes('$50,000 left') && !(await p.isVisible('#plOwnWrap')));
  await p.fill('#plAmt', '20000'); await p.keyboard.press('Enter');
  ck('budget pledge needs no attendee: recorded under the company', (await p.textContent('#plMsg')) === 'Recorded $20,000 for Ecomind from AMP.' && (await p.textContent('#pTotals')).includes('$30,000 left'));
  let asked = 0; p.on('dialog', () => asked++);
  await p.click('#plOrgs button >> nth=1'); await p.fill('#plAmt', '45000'); await p.keyboard.press('Enter');
  ck('going over the budget but inside the allowance records without asking', asked === 0 && (await p.textContent('#pTotals')).includes('$15,000 over'));
  await p.fill('#plAmt', '20000'); await p.keyboard.press('Enter');
  ck('going past the allowance asks first', asked === 1 && (await p.locator('.prow').count()) === 3);
  await p.click('#plSetupBtn'); await p.check('#psOwn'); await p.click('#psSave'); await p.check('#plOwn'); await p.fill('#plAmt', '100'); await p.keyboard.press('Enter');
  ck('own-money pledge in a budget event needs a donor', (await p.textContent('#plMsg')).includes('Choose who the pledge is from'));
  await p.fill('#plWho', 'Sam Smith'); await p.locator('#plSug button', { hasText: 'walk-in guest' }).click(); await p.keyboard.press('Enter');
  ck('own-money pledge does not touch the budget', (await p.textContent('#pTotals')).includes('$35,000 over') && (await p.locator('.prow').first().textContent()).includes('Sam Smith') && !(await p.locator('.prow').first().textContent()).includes('Budget'));
  await p.screenshot({ path: 'pledges-budget.png' });
  await p.click('#btnHome'); await p.locator('.ev', { hasText: 'TFN Flagship 1' }).locator('[data-act=open]').click(); await p.click('#navPlg');
  ck('each event keeps its own guests and pledges', (await p.locator('.prow').count()) === 4 && (await p.locator('#plOrgs button').count()) === 3);
  // ---------- export / import of an event carries them ----------
  await p.click('#navSet'); const [d3] = await Promise.all([p.waitForEvent('download'), p.click('#btnExport')]); await d3.saveAs(require('path').join(__dirname, 'out') + '/ev.json');
  const c2 = await b.newContext({ viewport: { width: 390, height: 800 } }); const q = await c2.newPage(); q.on('pageerror', e => errs.push('m ' + e));
  await q.goto(URL0); await q.setInputFiles('#file', require('path').join(__dirname, 'out') + '/ev.json'); await q.waitForSelector('.ev'); await q.click('.ev [data-act=open]'); await q.click('#navPlg');
  ck('exported event brings guests and pledges with it', (await q.locator('.prow').count()) === 4 && (await q.textContent('#pTotals')).includes('$23,750'));
  ck('phone width: pledges and guests pages fit', await q.evaluate(() => document.documentElement.scrollWidth <= innerWidth) && await (async () => { await q.click('#navGst'); return q.evaluate(() => document.documentElement.scrollWidth <= innerWidth); })());
  await q.screenshot({ path: 'guests390.png' });
  ck('no page errors', errs.length === 0); if (errs.length) console.log(errs);
  console.log(res.join('\n')); await b.close(); process.exit(res.some(r => r.startsWith('FAIL')) ? 1 : 0);
})().catch(e => { console.error(e); process.exit(2); });
